
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask mysql-connector-python
    
    - name: Run Tests
      run: |
        pytest tests/  # Assuming you have a tests folder with unit tests
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to UAT Server
      run: |
        scp -r * username@uat-server-ip:/path/to/deploy
        ssh username@uat-server-ip 'systemctl restart myapp'
